:whale: Initiate minimal working dockerfile and readme instructions
Code the dependencies needed for dat inside the docker container into the dockerfile.

Also added basic instructions for manually building the dockerfile, and running it. Currently prints out help message by default. Unable to `dat share` yet because of:

events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/.dat/secret_keys/b4/53bb98bd5e7a7ac97a5d3d407dd80d876619fc194941461376dfbe983629e4'